
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.2
    hooks:
      - id: pyupgrade
        args: [--py37-plus]

  - repo: https://github.com/omnilib/ufmt
    rev: v2.5.1
    hooks:
      - id: ufmt
        additional_dependencies:
          - black == 23.1.0
          - usort == 1.1.0b2

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
